// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC4tqe6gLGKRQYcnIHc_Vc1TM_OMG7buM',
    appId: '1:945305545409:web:5d63aa637fc9d6e0df0240',
    messagingSenderId: '945305545409',
    projectId: 'ssrk-81fdd',
    authDomain: 'ssrk-81fdd.firebaseapp.com',
    storageBucket: 'ssrk-81fdd.appspot.com',
    measurementId: 'G-SHQGN031K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ5n_qThfD4PHq4UsuZunVZw_2dJTEAfw',
    appId: '1:945305545409:android:4f21c548272270dfdf0240',
    messagingSenderId: '945305545409',
    projectId: 'ssrk-81fdd',
    storageBucket: 'ssrk-81fdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxx6AYjcxzDIKpA8Ah4r0Tb79N5g8rNPA',
    appId: '1:945305545409:ios:b5acce9dcc5ce6b8df0240',
    messagingSenderId: '945305545409',
    projectId: 'ssrk-81fdd',
    storageBucket: 'ssrk-81fdd.appspot.com',
    iosBundleId: 'com.example.projectssrk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxx6AYjcxzDIKpA8Ah4r0Tb79N5g8rNPA',
    appId: '1:945305545409:ios:ecc80ac2b6af92bedf0240',
    messagingSenderId: '945305545409',
    projectId: 'ssrk-81fdd',
    storageBucket: 'ssrk-81fdd.appspot.com',
    iosBundleId: 'com.example.projectssrk.RunnerTests',
  );
}
